config/routes.rb
require 'sidekiq/web'

Catarse::Application.routes.draw do
  def ssl_options
    if Rails.env.production? && CatarseSettings[:secure_host]
      {protocol: 'https', host: CatarseSettings[:secure_host]}
    else
      {}
    end
  end

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for(
    :users,
    {
      path: '',
      path_names:   { sign_in: :login, sign_out: :logout, sign_up: :sign_up },
      controllers:  { omniauth_callbacks: :omniauth_callbacks, passwords: :passwords },
      defaults: ssl_options
    }
  )


  devise_scope :user do
    post '/sign_up', {to: 'devise/registrations#create', as: :sign_up}.merge(ssl_options)
  end


  get '/thank_you' => "static#thank_you"


  check_user_admin = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin }

  filter :locale, exclude: /\/auth\//

  # Mountable engines
  constraints check_user_admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount CatarsePaypalExpress::Engine => "/", as: :catarse_paypal_express
  mount CatarseMoip::Engine => "/", as: :catarse_moip
  mount CatarseCredits::Engine => "/", as: :catarse_credits
  mount ZendeskEngine::Engine => "/", as: :zendesk
#  mount CatarseWepay::Engine => "/", as: :catarse_wepay

  # Channels
  constraints subdomain: /^(?!www|crowd|secure|test|local|bootstrap)(\w+)/ do
    namespace :channels, path: '' do
      namespace :admin do
        namespace :reports do
          resources :subscriber_reports, only: [ :index ]
        end
        resources :posts
        resources :partners
        resources :followers, only: [ :index ]
        resources :projects, only: [ :index, :update] do
          member do
            put 'approve'
            put 'reject'
            put 'push_to_draft'
            put 'push_to_trash'
          end
        end
      end

      resources :posts
      get '/', to: 'profiles#show', as: :profile
      get '/how-it-works', to: 'profiles#how_it_works', as: :about
      resource :profile
      resources :projects, only: [:new, :create, :show] do
        collection do
          get 'video'
        end
      end
      # NOTE We use index instead of create to subscribe comming back from auth via GET
      resource :channels_subscriber, only: [:show, :destroy], as: :subscriber
    end
  end

  # Root path should be after channel constraints
  root to: 'projects#index'

  get "/explore" => "explore#index", as: :explore

  namespace :reports do
    resources :contribution_reports_for_project_owners, only: [:index]
  end

  resources :projects, only: [:index, :create, :update, :new, :show] do
    resources :posts, controller: 'projects/posts', only: [ :index, :create, :destroy ]
    resources :rewards, only: [ :index, :create, :update, :destroy, :new, :edit ] do
      member do
        post 'sort'
      end
    end
    resources :contributions, {controller: 'projects/contributions'}.merge(ssl_options) do
      member do
        put 'credits_checkout'
      end
    end
    collection do
      get 'video'
    end
    member do
      put 'pay'
      get 'embed'
      get 'video_embed'
      get 'embed_panel'
      get 'send_to_analysis'
    end
  end
  resources :users do
    resources :projects, controller: 'users/projects', only: [ :index ]
    member do
      get :unsubscribe_notifications
      get :credits
      get :reactivate
    end
    collection do
      get :uservoice_gadget
    end
    resources :contributions, controller: 'users/contributions', only: [:index] do
      member do
        get :request_refund
      end
    end

    resources :unsubscribes, only: [:create]
    member do
      get 'projects'
      put 'unsubscribe_update'
      put 'update_email'
      put 'update_password', ssl_options
    end
  end

  namespace :admin do
    resources :projects, only: [ :index, :update, :destroy ] do
      member do
        put 'approve'
        put 'reject'
        put 'push_to_draft'
        put 'push_to_trash'
      end
    end

    resources :statistics, only: [ :index ]
    resources :financials, only: [ :index ]

    resources :contributions, only: [ :index, :update, :show ] do
      member do
        put 'confirm'
        put 'pendent'
        put 'change_reward'
        put 'refund'
        put 'hide'
        put 'cancel'
        put 'push_to_trash'
      end
    end
    resources :users, only: [ :index ]

    namespace :reports do
      resources :contribution_reports, only: [ :index ]
    end
  end

  get "/terms-of-use" => 'high_voltage/pages#show', id: 'terms_of_use'
  get "/privacy-policy" => 'high_voltage/pages#show', id: 'privacy_policy'

  get "/:permalink" => "projects#show", as: :project_by_slug


end

app/controllers/admin/financials_controller.rb
class Admin::FinancialsController < Admin::BaseController
  layout 'catarse_bootstrap'
  inherit_resources
  defaults  resource_class: Project, collection_name: 'projects', instance_name: 'project'

  has_scope :by_permalink, :name_contains, :user_name_contains, :financial, :with_state, :by_progress
  has_scope :between_expires_at, using: [ :start_at, :ends_at ], allow_blank: true

  respond_to :html, :csv

  actions :index

  def index
    respond_to do |format|
      format.html {collection}
      format.csv do
        financials = ProjectFinancial.where(project_id: projects.select("id"))

        self.response_body = Enumerator.new do |y|
          financials.copy_to do |line|
            y << line
          end
        end
      end
    end
  end

  protected
  def projects
    apply_scopes(Project).includes(:user).order("CASE state WHEN 'successful' THEN 1 WHEN 'waiting_funds' THEN 2 ELSE 3 END, (projects.expires_at)::date DESc")
  end

  def collection
    @scoped_projects = projects
    @projects ||= @scoped_projects.page(params[:page])
  end
end

app/views/catarse_bootstrap/admin/financials/index.html.slim
= render 'shared/header'
.row.admin
  h1= @title = t('.title')
  = simple_form_for '', url: admin_financials_path, method: :get do |form|
    .row
      .large-2.columns
        = form.input :by_permalink, as: :string, label: t('.permalink'), input_html: {value: params[:by_permalink]}
      .large-2.columns
        = form.input "between_expires_at[start_at]", as: :string, label: t(".between_expires_at"), input_html: {value: params[:between_expires_at] && params[:between_expires_at][:start_at], data: { mask: '99/99/9999' } }
      .large-2.columns.no-label
        = form.input "between_expires_at[ends_at]", as: :string, label: '', input_html: {value: params[:between_expires_at] && params[:between_expires_at][:ends_at], data: { mask: '99/99/9999' } }
      .large-2.columns
        = form.input :by_progress, as: :string, label: t('.by_progress'), input_html: {value: params[:by_progress]}
      .large-2.columns
        = form.input :name_contains, as: :string, label: t('.project'), input_html: {value: params[:name_contains]}
      .large-2.columns
        = form.input :user_name_contains, as: :string, label: t('.user'), input_html: {value: params[:user_name_contains]}

    .row
      .large-2.columns
        = form.input :with_state, collection: Project.state_names, label: t('channels.admin.filter.with_state'), as: :select, selected: params[:with_state], include_blank: true

      .large-2.columns.search_report
        = link_to t('.search_report'), admin_financials_path(params: params,format: :csv)
      .large-2.large-offset-1.columns
        = form.button :submit, t('channels.admin.filter.submit'), class: 'button medium negative'

    .row
      .large-2.large-offset-10.columns
        p.filtered-number = @scoped_projects.count(:all)
        p.filtered-number-label
          = pluralize_without_number(@scoped_projects.count(:all), t('project_singular'), t('project_plural'))
          '
          = pluralize_without_number @scoped_projects.count(:all), t('found_singular'), t('found_plural')

  = paginate @projects
  - if @projects.empty?
    = t('.no_projects')
  - else
    table.table.table-striped
      thead
        tr
          th style="width: 200px;"
            = t('.name')
          th= t('.user')
          th= t('.goal')
          th= t('.pledged')
          th= t('.total_payment_service_fee')
          th= t('.total_catarse_fee')
          th= t('.repass_value')
          th= t('.expires_at')
          th= t('.reports')
          th= t('.state')
          th
      tbody
        - @projects.each do |project|
          tr id=project.id class=cycle("even", "odd")
            td= link_to project.name, project_by_slug_path(permalink: project.permalink), target: '_blank'
            td= link_to (project.user.moip_login.blank? ? 'Não preenchido' : project.user.moip_login), user_path(project.user, anchor: :settings), target: '_blank'
            td= project.display_goal
            td= project.display_pledged
            td= number_to_currency project.total_payment_service_fee, precision: 2
            - catarse_fee = CatarseSettings[:catarse_fee].to_f * project.pledged
            td
              = number_to_currency catarse_fee, precision: 2
            td
              = number_to_currency ((project.pledged*0.87)), precistion: 2
            td
              = project.display_expires_at
            td
              = link_to t('.contribution_report'), admin_reports_contribution_reports_path(project_id: project.id, format: :csv)
            td
              - if project.online?
                span.label.label-online= project.state
              - elsif project.successful?
                span.label.label-success= project.state
              - elsif project.failed? or project.rejected?
                span.label.label-important= project.state
              - elsif project.waiting_funds?
                span.label.label-warning= project.state
              - else
                span.label= project.state

  = paginate @projects
= render 'shared/footer'