config/routes.rb
require 'sidekiq/web'

Catarse::Application.routes.draw do
  def ssl_options
    if Rails.env.production? && CatarseSettings[:secure_host]
      {protocol: 'https', host: CatarseSettings[:secure_host]}
    else
      {}
    end
  end

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for(
    :users,
    {
      path: '',
      path_names:   { sign_in: :login, sign_out: :logout, sign_up: :sign_up },
      controllers:  { omniauth_callbacks: :omniauth_callbacks, passwords: :passwords },
      defaults: ssl_options
    }
  )


  devise_scope :user do
    post '/sign_up', {to: 'devise/registrations#create', as: :sign_up}.merge(ssl_options)
  end


  get '/thank_you' => "static#thank_you"


  check_user_admin = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin }

  filter :locale, exclude: /\/auth\//

  # Mountable engines
  constraints check_user_admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount CatarsePaypalExpress::Engine => "/", as: :catarse_paypal_express
  mount CatarseMoip::Engine => "/", as: :catarse_moip
  mount CatarseCredits::Engine => "/", as: :catarse_credits
  mount ZendeskEngine::Engine => "/", as: :zendesk
#  mount CatarseWepay::Engine => "/", as: :catarse_wepay

  # Channels
  constraints subdomain: /^(?!www|crowd|secure|test|local|bootstrap)(\w+)/ do
    namespace :channels, path: '' do
      namespace :admin do
        namespace :reports do
          resources :subscriber_reports, only: [ :index ]
        end
        resources :posts
        resources :partners
        resources :followers, only: [ :index ]
        resources :projects, only: [ :index, :update] do
          member do
            put 'approve'
            put 'reject'
            put 'push_to_draft'
            put 'push_to_trash'
          end
        end
      end

      resources :posts
      get '/', to: 'profiles#show', as: :profile
      get '/how-it-works', to: 'profiles#how_it_works', as: :about
      resource :profile
      resources :projects, only: [:new, :create, :show] do
        collection do
          get 'video'
        end
      end
      # NOTE We use index instead of create to subscribe comming back from auth via GET
      resource :channels_subscriber, only: [:show, :destroy], as: :subscriber
    end
  end

  # Root path should be after channel constraints
  root to: 'projects#index'

  get "/explore" => "explore#index", as: :explore

  namespace :reports do
    resources :contribution_reports_for_project_owners, only: [:index]
  end

  resources :projects, only: [:index, :create, :update, :new, :show] do
    resources :posts, controller: 'projects/posts', only: [ :index, :create, :destroy ]
    resources :rewards, only: [ :index, :create, :update, :destroy, :new, :edit ] do
      member do
        post 'sort'
      end
    end
    resources :contributions, {controller: 'projects/contributions'}.merge(ssl_options) do
      member do
        put 'credits_checkout'
      end
    end
    collection do
      get 'video'
    end
    member do
      put 'pay'
      get 'embed'
      get 'video_embed'
      get 'embed_panel'
      get 'send_to_analysis'
    end
  end
  resources :users do
    resources :projects, controller: 'users/projects', only: [ :index ]
    member do
      get :unsubscribe_notifications
      get :credits
      get :reactivate
    end
    collection do
      get :uservoice_gadget
    end
    resources :contributions, controller: 'users/contributions', only: [:index] do
      member do
        get :request_refund
      end
    end

    resources :unsubscribes, only: [:create]
    member do
      get 'projects'
      put 'unsubscribe_update'
      put 'update_email'
      put 'update_password', ssl_options
    end
  end

  namespace :admin do
    resources :projects, only: [ :index, :update, :destroy ] do
      member do
        put 'approve'
        put 'reject'
        put 'push_to_draft'
        put 'push_to_trash'
      end
    end

    resources :statistics, only: [ :index ]
    resources :financials, only: [ :index ]

    resources :contributions, only: [ :index, :update, :show ] do
      member do
        put 'confirm'
        put 'pendent'
        put 'change_reward'
        put 'refund'
        put 'hide'
        put 'cancel'
        put 'push_to_trash'
      end
    end
    resources :users, only: [ :index ]

    namespace :reports do
      resources :contribution_reports, only: [ :index ]
    end
  end

  get "/terms-of-use" => 'high_voltage/pages#show', id: 'terms_of_use'
  get "/privacy-policy" => 'high_voltage/pages#show', id: 'privacy_policy'

  get "/:permalink" => "projects#show", as: :project_by_slug


end

app/models/concerns/project/custom_validators.rb
module Project::CustomValidators
  extend ActiveSupport::Concern

  included do
    validate :permalink_cant_be_route, allow_nil: true

    def self.permalink_on_routes?(permalink)
      permalink && self.get_routes.include?(permalink.downcase)
    end

    def permalink_cant_be_route
      errors.add(:permalink, I18n.t("activerecord.errors.models.project.attributes.permalink.invalid")) if Project.permalink_on_routes?(permalink)
    end
  end
end

app/models/concerns/project/state_machine_handler.rb
module Project::StateMachineHandler
  extend ActiveSupport::Concern

  included do
    #NOTE: state machine things
    state_machine :state, initial: :draft do
      state :draft, value: 'draft'
      state :rejected, value: 'rejected'
      state :online, value: 'online'
      state :successful, value: 'successful'
      state :waiting_funds, value: 'waiting_funds'
      state :failed, value: 'failed'
      state :deleted, value: 'deleted'
      state :in_analysis, value: 'in_analysis'

      event :push_to_draft do
        transition all => :draft #NOTE: when use 'all' we can't use new hash style ;(
      end

      event :push_to_trash do
        transition [:draft, :rejected, :in_analysis] => :deleted
      end

      event :send_to_analysis do
        transition draft: :in_analysis
      end

      event :reject do
        transition in_analysis: :rejected
      end

      event :approve do
        transition in_analysis: :online
      end

      event :finish do
        transition online: :failed,             if: ->(project) {
          project.should_fail? && !project.pending_contributions_reached_the_goal?
        }

        transition online: :waiting_funds,      if: ->(project) {
          project.expired? && project.pending_contributions_reached_the_goal?
        }

        transition waiting_funds: :successful,  if: ->(project) {
          project.reached_goal? && !project.in_time_to_wait?
        }

        transition waiting_funds: :failed,      if: ->(project) {
          project.should_fail? && !project.in_time_to_wait?
        }

        transition waiting_funds: :waiting_funds,      if: ->(project) {
          project.should_fail? && project.in_time_to_wait?
        }
      end

      after_transition do |project, transition|
        project.notify_observers :"from_#{transition.from}_to_#{transition.to}"
      end

      after_transition any => [:failed, :successful] do |project, transition|
        project.notify_observers :sync_with_mailchimp
      end

      after_transition [:draft, :rejected] => :deleted do |project, transition|
        project.update_attributes({ permalink: "deleted_project_#{project.id}"})
      end
    end
  end
end

app/models/concerns/project/video_handler.rb
module Project::VideoHandler
  extend ActiveSupport::Concern
  include Shared::VideoHandler

  included do
    mount_uploader :video_thumbnail, ProjectUploader

    def download_video_thumbnail
      self.video_thumbnail = open(self.video.thumbnail_large)  if self.video_valid?
      self.save
    rescue OpenURI::HTTPError, TypeError => e
      Rails.logger.info "-----> #{e.inspect}"
    end
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController
  layout 'catarse_bootstrap'

  has_scope :by_user_email, :by_id, :pg_search, :user_name_contains, :with_state, :by_category_id, :order_by
  has_scope :between_created_at, :between_expires_at, :between_online_date, :between_updated_at, :goal_between, using: [ :start_at, :ends_at ]

  before_filter do
    @total_projects = Project.count(:all)
  end

  [:approve, :reject, :push_to_draft, :push_to_trash].each do |name|
    define_method name do
      @project = Project.find params[:id]
      @project.send("#{name.to_s}!")
      redirect_to :back
    end
  end

  def destroy
    @project = Project.find params[:id]
    if @project.can_push_to_trash?
      @project.push_to_trash!
    end

    redirect_to admin_projects_path
  end

  protected
  def collection
    @scoped_projects = apply_scopes(end_of_association_chain).with_project_totals.without_state('deleted')
    @projects = @scoped_projects.page(params[:page])
  end
end

app/controllers/channels/admin/projects_controller.rb
class Channels::Admin::ProjectsController < Admin::BaseController
  layout 'catarse_bootstrap'
  has_scope :by_id, :pg_search, :user_name_contains, :order_by, :with_state
  has_scope :between_created_at, using: [ :start_at, :ends_at ], allow_blank: true

  before_filter do
    @total_projects =  channel.projects.size
  end

  [:approve, :reject, :push_to_draft, :push_to_trash].each do |name|
    define_method name do
      @project    = channel.projects.find(params[:id])
      @project.send("#{name.to_s}!")
      redirect_to :back
    end
  end

  protected
  def begin_of_association_chain
    channel
  end

  def collection
    @projects = apply_scopes(channel.projects.page(params[:page]))
  end
end

app/controllers/channels/projects_controller.rb
class Channels::ProjectsController < ProjectsController
  layout 'catarse_bootstrap'
  belongs_to :channel, finder: :find_by_permalink!, param: :profile_id


  # Inheriting from the original Projects controller
  # With one addition: we include the project into the current channel
  before_filter only: [:create] { params[:project][:channels] = [channel] }

  prepend_before_filter{ params[:profile_id] = request.subdomain }
end

app/controllers/projects/contributions_controller.rb
class Projects::ContributionsController < ApplicationController
  inherit_resources
  actions :index, :show, :new, :update, :review, :create
  skip_before_filter :force_http
  skip_before_filter :verify_authenticity_token, only: [:moip]
  has_scope :available_to_count, type: :boolean
  has_scope :with_state
  has_scope :page, default: 1
  after_filter :verify_authorized, except: [:index]
  belongs_to :project
  before_filter :detect_old_browsers, only: [:new, :create]

  helper_method :avaiable_payment_engines

  def edit
    authorize resource
  end

  def update
    authorize resource
    resource.update_attributes(permitted_params[:contribution])
    resource.update_user_billing_info
    render json: {message: 'updated'}
  end

  def index
    render collection
  end

  def show
    authorize resource
    @title = t('projects.contributions.show.title')
  end

  def new
    @contribution = Contribution.new(project: parent, user: current_user)
    authorize @contribution

    @title = t('projects.contributions.new.title', name: @project.name)
    empty_reward = Reward.new(minimum_value: 0, description: t('projects.contributions.new.no_reward'))
    @rewards = [empty_reward] + @project.rewards.remaining.order(:minimum_value)

    # Select
    if params[:reward_id] && (@selected_reward = @project.rewards.find params[:reward_id]) && !@selected_reward.sold_out?
      @contribution.reward = @selected_reward
      @contribution.value = "%0.0f" % @selected_reward.minimum_value
    end
  end

  def create
    @title = t('projects.contributions.create.title')
    @contribution = Contribution.new(params[:contribution].merge(user: current_user, project: parent))
    @contribution.reward_id = nil if params[:contribution][:reward_id].to_i == 0
    authorize @contribution
    create! do |success,failure|
      failure.html do
        flash[:failure] = t('projects.contributions.review.error')
        return redirect_to new_project_contribution_path(@project)
      end
      success.html do
        resource.update_current_billing_info
        flash[:notice] = nil
        session[:thank_you_contribution_id] = @contribution.id
        return redirect_to edit_project_contribution_path(project_id: @project.id, id: @contribution.id)
      end
    end
    @thank_you_id = @project.id
  end

  protected
  def permitted_params
    params.permit(policy(resource).permitted_attributes)
  end

  def avaiable_payment_engines
    @engines ||= PaymentEngines.engines.inject([]) do |total, item|
      if item.name == 'Credits' && current_user.credits > 0
        total << item
      elsif item.name != 'Credits'
        total << item
      end

      total
    end
  end

  def collection
    @contributions ||= apply_scopes(end_of_association_chain).available_to_display.order("confirmed_at DESC").per(10)
  end
end

app/controllers/projects/posts_controller.rb
class Projects::PostsController < ApplicationController
  after_filter :verify_authorized, except: %i[index show]
  after_action :verify_policy_scoped, only: %i[index]
  inherit_resources

  actions :index, :create, :destroy
  belongs_to :project

  def show
    render resource
  end

  def index
    render collection.page(params[:page]).per(3)
  end

  def create
    @post = parent.posts.new(post_params)
    authorize @post
    @post.save
    render @post
  end

  def destroy
    authorize resource
    destroy!{ return index }
  end

  def collection
    @posts ||= policy_scope(end_of_association_chain).ordered
  end

  protected

  def post_params
    params.require(:project_post).permit(:title, :comment, :user_id, :exclusive).merge!(user_id: current_user.try(:id))
  end

end

app/controllers/projects_controller.rb
# coding: utf-8
class ProjectsController < ApplicationController
  after_filter :verify_authorized, except: %i[index video video_embed embed embed_panel]
  inherit_resources
  has_scope :pg_search, :by_category_id, :near_of
  has_scope :recent, :expiring, :successful, :in_funding, :recommended, :not_expired, type: :boolean

  respond_to :html
  respond_to :json, only: [:index, :show, :update]

  def index
    index! do |format|
      format.html do
        if request.xhr?
          @projects = apply_scopes(Project.visible.order_status)
            .most_recent_first
            .includes(:project_total, :user, :category)
            .page(params[:page]).per(6)
          return render partial: 'project', collection: @projects, layout: false
        else
          @title = t("site.title")
          if current_user && current_user.recommended_projects.present?
            @recommends = current_user.recommended_projects.limit(3)
          else
            @recommends = ProjectsForHome.recommends
          end

          @projects_near = Project.with_state('online').near_of(current_user.address_state).order("random()").limit(3) if current_user
          @expiring = ProjectsForHome.expiring
          @recent   = ProjectsForHome.recents
        end
      end
    end
  end

  def new
    @project = Project.new user: current_user
    authorize @project
    @title = t('projects.new.title')
    @project.rewards.build
  end

  def create
    @project = Project.new params[:project].merge(user: current_user)
    authorize @project
    create! { project_by_slug_path(@project.permalink) }
  end

  def destroy
    authorize resource
    destroy!
  end

  def send_to_analysis
    authorize resource
    resource.send_to_analysis
    if referal_link.present?
      resource.update_attribute :referal_link, referal_link
    end
    flash[:notice] = t('projects.send_to_analysis')
    redirect_to project_by_slug_path(@project.permalink)
  end

  def update
    authorize resource
    update! do |format|
      format.html do
        if resource.errors.present?
          flash[:alert] = resource.errors.full_messages.to_sentence
        else
          flash[:notice] = t('project.update.success')
        end

        redirect_to project_by_slug_path(@project.reload.permalink, anchor: 'edit')
      end
    end
  end

  def show
    @title = resource.name
    authorize @project
    fb_admins_add(resource.user.facebook_id) if resource.user.facebook_id
    @posts_count = resource.posts.count(:all)
    @post = resource.posts.where(id: params[:project_post_id]).first if params[:project_post_id].present?
  end

  def video
    project = Project.new(video_url: params[:url])
    render json: project.video.to_json
  rescue VideoInfo::UrlError
    render json: nil
  end

  %w(embed video_embed).each do |method_name|
    define_method method_name do
      @title = resource.name
      render layout: 'embed'
    end
  end

  def embed_panel
    @title = resource.name
    render layout: false
  end

  protected

  def permitted_params
    params.permit(policy(resource).permitted_attributes)
  end

  def resource
    @project ||= (params[:permalink].present? ? Project.by_permalink(params[:permalink]).first! : Project.find(params[:id]))
  end

  def use_catarse_boostrap
    action_name == "new" || action_name == "create" ? 'catarse_bootstrap' : 'application'
  end
end

app/controllers/users/projects_controller.rb
class Users::ProjectsController < ApplicationController
  after_filter :verify_authorized, except: [:index]
  after_filter :verify_policy_scoped, only: [:index]

  inherit_resources
  actions :index
  belongs_to :user

  def index
    collection
    render layout: false
  end

  protected

  def policy_scope(scope)
    @_policy_scoped = true
    ProjectPolicy::UserScope.new(current_user, parent, scope).resolve
  end

  def collection
    @projects ||= policy_scope(end_of_association_chain).page(params[:page]).per(10)
  end

end

app/views/projects/_draft_warning.html.slim
br
- if policy(@project).update?
  #project_warning.bootstrap-alert
    .alert.alert-warning
      i Bem-vindo ao Rascunho!
      #toggle_warning
        = link_to '(minimizar informações)', '#'
      #project_warning_text
        br/
        br/
        | Para editar a página do seu projeto procure abaixo pela <strong>aba de EDIÇÃO</strong>, realize todas as alterações no formulário e clique em <strong>ATUALIZAR INFORMAÇÕES</strong>.
        br/
        | As recompensas podem ser adicionadas diretamente na coluna onde ficam expostas, para isso basta clicar em <strong>ADICIONAR RECOMPENSA</strong>. 
        br/
        br/
        strong Importante!
        br/
        | Seu projeto só será avaliado pela nossa equipe quando você clicar no botão <strong>ENVIAR PROJETO</strong>. Iremos analisar a consistência do seu projeto apenas com base nas informações presentes no seu rascunho, 
        | por isso seja bastante claro e objetivo na construção desta página. O <strong>vídeo</strong> não é obrigatório para a avaliação, apenas para o projeto ir ao ar. 
        | Caso você já o tenha pronto, disponibilize pra gente. Quanto mais informação para o nosso atendimento e avaliação, melhor. Não deixe de estudar os 
        | artigos da nossa #{link_to 'Central de Suporte!', CatarseSettings[:support_forum], target: '__blank'} Lá você pode se informar sobre a maioria dos processos que ocorrem antes, durante e depois de uma campanha no Catarse!
        br/
        br/
        strong Solução de problemas:
        br/
        | Confira: #{link_to 'Realizadores - Primeiros Passos', 'http://suporte.catarse.me/hc/pt-br/sections/200406978-Realizadores-Primeiros-passos', target: '__blank'}
      br/
      br/
      .bootstrap-twitter
        = link_to 'Enviar projeto', send_to_analysis_project_path(@project), class: 'btn btn-large'
- else
  #project_warning.bootstrap-alert
    .alert.alert-warning
      i Atenção! Este projeto ainda está em rascunho.
      #toggle_warning
        = link_to '(minimizar informações)', '#'
      #project_warning_text
        br/
        br/
        | Este projeto ainda não está apto a receber contribuições financeiras e as informações dessa página não são definitivas. 
        | Se você quer dar uma força desde já, deixe seu feedback para o(a) realizador(a) na <strong>Aba de Comentários</strong>.

app/views/projects/_in_analysis_warning.html.slim
br
- if policy(@project).update?
  #project_warning.bootstrap-alert
    .alert.alert-warning
      i Seu projeto está em análise.
      #toggle_warning
        = link_to '(minimizar informações)', '#'
      #project_warning_text
        br/
        br/
        | Estamos avaliando as informações do seu rascunho, entraremos em contato em até 4 dias úteis =) 
        br/
        | Lembre-se de preencher as informações do #{link_to 'seu perfil', user_path(@project.user)} no Catarse
        br/
        br/
        strong Solução de problemas:
        br/
        = link_to 'Socorro! | Já passaram 4 dias úteis e não tive noticias da curadoria, o que fazer?', 'http://suporte.catarse.me/hc/pt-br/articles/202037423-Socorro-J%C3%A1-enviei-o-projeto-h%C3%A1-quatro-dias-%C3%BAteis-e-n%C3%A3o-me-respondem-', target: '__blank'
- else
  #project_warning.bootstrap-alert
    .alert.alert-warning
      i Atenção! Este projeto ainda não está no ar! O Realizador responsável está fazendo ajustes! 
      #toggle_warning
        = link_to '(minimizar informações)', '#'
      #project_warning_text
        br/
        br/
        | Aproveite para dar uma olhada na página e deixe seu feedback para o(a) realizador(a) ali na <strong>Aba Comentários</strong>. Ajude a melhorar o projeto com a sua opinião! 

app/views/projects/_project_about.html.slim
.media
  .video
    iframe src="#{@project.display_video_embed_url}" width="640" height="430" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen
  .social
    #project_share
      #facebook_share= render_facebook_like title: @project.name, href: project_by_slug_url(@project.permalink, locale: I18n.locale)
      ul
        li.embed
          = link_to '#embed', id: 'embed_link' do
            = image_tag "catarse/embed_icon19x9.png", title: t('.embed_title')
            = t('.embed')
      #twitter_share= render_twitter(url: project_by_slug_url(permalink: @project.permalink), title: @project.name)
      .clearfix

.clearfix
#project_embed.hide data-path=embed_panel_project_path(@project)
  = image_tag "loading.gif", class: 'loader'
.text
  p
    = @project.about_html.html_safe

app/views/projects/embed.html.slim
#embed
  = render partial: 'project', locals: { project: @project, embed_link: true }

app/views/projects/embed_panel.html.slim
- box_width = "240px"
- box_height = "425px"
- video_width = "384px"
- video_height = "425px"
#project_box_embed
  iframe frameborder='0' height=box_height width=box_width src=embed_project_path(@project)
  form.html= text_area_tag 'project_box_embed_html', '<iframe frameborder="0" height="' + box_height + '" src="' + embed_project_url(@project) + '" width="' + box_width + '"></iframe>', readonly: true
#project_video_embed
  iframe frameborder='0' height=video_height width=video_width src=video_embed_project_path(@project)
  form.html= text_area_tag 'project_video_embed_html', '<iframe frameborder="0" height="' + video_height + '" src="' + video_embed_project_url(@project) + '" width="' + video_width + '"></iframe>', readonly: true
.clearfix

app/views/projects/show.html.slim
= content_for :meta_tags do
  - if ['online', 'waiting_funds', 'successful'].include? @project.state
    meta name="robots" content="index, follow"
  - else
    meta name="robots" content="noindex, nofollow"

  - if @post
    meta name="description" content=@post.title
    meta property="og:title" content=@post.title
    meta property="og:description" content=@post.comment
    meta property="og:url" content=project_by_slug_url(@project.permalink, update_id: @post.id, locale: I18n.locale)
  - else
    meta name="description" content=@project.headline
    meta property="og:title" content=@project.name
    meta property="og:description" content=@project.headline
    meta property="og:url" content=project_by_slug_url(@project.permalink, locale: I18n.locale)
  meta property="og:type" content='cause'
  meta property="og:image" content=@project.display_image('project_thumb_facebook')
  meta property="og:site_name" content=CatarseSettings[:company_name]
  meta property="fb:admins" content="#{fb_admins}"
  
#page_content
  .container

    = render @project.state_warning_template

    #project_description
    .project_image
      = image_tag @project.display_image('project_thumb_small')
    .section_header
      h1= @project.name
      h4
        = t('.project_header.without_city')
        |&nbsp;
        = link_to(@project.category, explore_path(anchor: "by_category_id/#{@project.category_id}"))
        |&nbsp;
        = t('projects.index.box.by')
        |&nbsp;
        = link_to(@project.user.display_name, user_path(@project.user))
        |&nbsp;
        - @project.channels.each do |c|
          = link_to(c.name, root_url(subdomain: c.permalink), class: 'project-channel')
    .tab_container
      nav#project_menu
        = link_to '#about', 'id' => 'about_link', 'class' => 'selected', 'data-target' => '#project_about.content' do
          = t('.menu.about')
        = link_to '#posts', 'id' => 'posts_link', 'data-target' => '#project_posts' do
          = t('.menu.posts')
          span.count=" (#{@posts_count})"
        = link_to '#contributions', 'id' => 'contributions_link', 'data-target' => '#project_contributions' do
          = t('.menu.contributions')
          span.count=" (#{@project.total_contributions})"
        = link_to '#comments', 'id' => 'comments_link', 'data-target' => '#project_comments' do
          = t('.menu.comments')
          | &nbsp; (
          / we need to remove the locale from the url
          fb:comments-count href="#{request.base_url}/#{request.fullpath.split('/')[2]}"
          | )
        - if policy(@project).update?
          = link_to '#edit', 'id' => 'edit_link', 'data-target' => '#project_edit' do
            = t('.menu.edit')
          = link_to '#reports', 'id' => 'reports_link', 'data-target' => '#project_reports' do
            = t('.menu.reports')
    .main
      #project_content
        - if policy(@project).update?
          #project_reports.content.hide
            = render partial: 'project_reports'
          #project_edit.content.hide
            = render partial: 'project_edit'

        #project_posts.content.hide[data-path=project_posts_path(project_id: @project.id)]
          - if policy(@project).update?
            = render template: 'projects/posts/new'
          .results &nbsp;
          .clearfix
          #posts-loading.loading= image_tag "loading.gif"
        #project_contributions.content.hide[data-path=project_contributions_path(project_id: @project.id)]
          - if policy(@project).update?
            = radio_button_tag(:contribution_state, "available_to_count", checked: true)
            = label_tag(:contribution_state, t('.contribution_states.confirmed'))
            = radio_button_tag(:contribution_state, "waiting_confirmation")
            = label_tag(:contribution_state, t('.contributions_states.pending'))
          .results &nbsp;
          .clearfix
          #contributions-loading.loading= image_tag "loading.gif"
        #project_comments.content.hide
        #project_about.content= render 'project_about'

      .clearfix
    .sidebar
      .info
        #statistics
          .statistics
            .item.contributions
              p= @project.total_contributions
              em= t('.sidebar.contributions')
            .item.goal
              p= @project.display_pledged
              em= t('.sidebar.goal', total: @project.display_goal).html_safe
            .item.time
              - if @project.draft? || @project.rejected?
                p= @project.online_days
                em #{@project.online_days} #{pluralize_without_number(@project.online_days, I18n.t('datetime.prompts.day').downcase)} #{pluralize_without_number(@project.online_days, t('remaining_singular'), t('remaining_plural'))}
              - else
                p= @project.remaining_days
                em #{@project.time_to_go[:unit].capitalize} #{pluralize_without_number(@project.time_to_go[:time], t('remaining_singular'), t('remaining_plural'))}

          #condition[class="#{@project.display_status}"]
            p
              = t(".contribute_project.display_status.#{@project.display_status}", goal: @project.display_goal, date: @project.display_expires_at)
          - if @project.online? && !@project.expired?
            #pledge
              = form_tag(new_project_contribution_path(@project), method: :get, id: 'contribute_project_form') do
                fieldset
                  = submit_tag t('.contribute_project.submit'), disabled: (not @project.online?)
        #creator_profile
          h3= t('.project_by')
          .avatar = @project.user.display_image_html width: 80, height: 80
          .personal_info
            p.name
             = link_to @project.user.display_name, user_path(@project.user)
            #bio
              p= @project.user.bio
          #city
            p.contribution= t('.count_contributed_projects', total: @project.user.total_contributed_projects)
            p.city
              | #{@project.user.address_city}
        .user_social
          ul
            - if @project.user.facebook_link
              li
                = link_to "Perfil no facebook", @project.user.facebook_link, target: '_blank', class: 'facebook'
            - if @project.user.twitter
              li
                = link_to "Perfil no twitter", @project.user.twitter_link, target: '_blank', class: 'twitter'
            - if @project.user.email
              li
                = mail_to @project.user.email, @project.user.email, target: '_blank', class: 'email'
            - if @project.user.other_link
              li.other
                = link_to @project.user.other_link, @project.user.other_link, target: '_blank'

        .clearfix
        - if policy(@project).update?
          .bootstrap-twitter.bootstrap-form
            .alert.alert-info
              h4.alert-header= t('.no_rewards_warning_title')
              p style="margin:0; padding:0;"
                = t('.no_rewards_warning')
              br/
              .new_reward_content.hide
                = image_tag 'loading.gif'

            .clearfix
            = link_to t('.menu.add_reward'), 'javascript:void(0);', data: {target: '.new_reward_content', path: new_project_reward_path(@project)}, class: 'btn btn-success pull-right show_reward_form'
            .clearfix

            br/
            /.skull-modal.new_reward_content.hide
              .skull-modal-header
                h3= t('projects.rewards.new_reward')
                a class='skull-modal-close' href='javascript:void(0);' &times;
              .skull-modal-body
                = image_tag 'loading.gif'
        #rewards[data-can_update="#{policy(@project).update?}" data-index_path=project_rewards_path(@project)]
          .reward-loader= image_tag 'loading.gif'
        .funding_period_title
          = t('.funding_period')
        .funding_period
          = "#{@project.display_online_date} - #{@project.display_expires_at} (#{t('datetime.distance_in_words.x_days', count: @project.online_days)})"

    .clearfix